# Generated by Django 3.1.7 on 2021-03-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0002_auto_20210319_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workout',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='heightInInches',
            new_name='height_in_inches',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False)),
                ('calories', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'workout_session',
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='completedWorkouts',
            field=models.ManyToManyField(to='keepfit.WorkoutSession'),
        ),
    ]
