# Generated by Django 3.1.7 on 2021-03-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0004_auto_20210322_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_date',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='end_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='start_time',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='savedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'saved_workouts',
            },
        ),
        migrations.CreateModel(
            name='likedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'liked_workouts',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='keepfit.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='keepfit.user')),
            ],
            options={
                'db_table': 'followings',
            },
        ),
        migrations.CreateModel(
            name='completedWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'completed_workouts',
            },
        ),
    ]
