# Generated by Django 3.1.7 on 2021-03-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0005_auto_20210324_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
