# Generated by Django 3.1.7 on 2021-03-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0006_auto_20210324_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedworkout',
            name='saver_id',
        ),
        migrations.RemoveField(
            model_name='savedworkout',
            name='workout_id',
        ),
        migrations.DeleteModel(
            name='completedWorkout',
        ),
        migrations.DeleteModel(
            name='savedWorkout',
        ),
    ]
