# Generated by Django 3.1.7 on 2021-03-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0008_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
