# Generated by Django 3.1.7 on 2021-04-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0010_user_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False)),
                ('date', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
    ]
