# Generated by Django 3.1.5 on 2021-04-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0011_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='searchItem',
            field=models.CharField(default=0.0, max_length=9999),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlannedWorkout',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False)),
                ('date', models.FloatField()),
                ('planner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'planned_Workouts',
            },
        ),
    ]
