# Generated by Django 3.1.5 on 2021-04-30 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0012_auto_20210414_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comment_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(max_length=9999, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=9999)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.workout')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
