# Generated by Django 3.1.5 on 2021-04-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0013_auto_20210430_1644'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
