# Generated by Django 3.1.5 on 2021-05-01 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keepfit', '0014_auto_20210430_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.FloatField()),
                ('creatorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keepfit.user')),
            ],
            options={
                'db_table': 'livestream',
            },
        ),
    ]
